# Use the official MySQL image as the base image
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=todo_db

# Copy the initialization script to the container
COPY ./init.sql /docker-entrypoint-initdb.d/init.sql

# Expose the default MySQL port
EXPOSE 3306

# Set the volume for MySQL data
VOLUME /var/lib/mysql

# Start MySQL server
CMD ["mysqld"]
